import { Poppins } from 'next/font/google';
import "./globals.css";
import QueryProvider from './components/QueryProvider';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'], 
});


export const metadata = {
  title: "Weather App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
       className={`${poppins.className} antialiased`}
      >
      <QueryProvider>
      {children}
    </QueryProvider>
      </body>
    </html>
  );
}
